core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls', namespace="todos"))
]

todos/urls.py
from django.urls import path
from . import views

app_name = "todos"
urlpatterns = [
    path("", views.todo_list, name="todo-list"),
    path("create/", views.todo_create, name="todo-create"),
    path("done/<int:todo_id>/", views.todo_done_undone, name="todo-done-undone"),
    path("delete/<int:todo_id>/", views.todo_delete, name="todo-delete"),
]

todos/models.py
from django.db import models


# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    done = models.BooleanField(default=False)

    def __str__(self):
        return self.title

todos/forms.py
from django import forms
from todos.models import Todo


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ('title', 'description', 'done')

todos/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_http_methods
from todos.forms import TodoForm
from todos.models import Todo


# Create your views here.
@require_http_methods(["GET"])
def todo_list(request):
    context = {
        'todos': Todo.objects.all(),
        'form': TodoForm()
    }
    return render(request, context=context, template_name="todos/todo-list.html")


@require_http_methods(["POST"])
def todo_create(request):
    form = TodoForm(data=request.POST)

    if form.is_valid():
        todo = form.save()
        context = {
            'todo': todo
        }
        return render(request, template_name="todos/todo-list.html#todo-list-item", context=context)


@require_http_methods(["POST"])
def todo_done_undone(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.done = not todo.done
    todo.save()

    context = {
        'todo': todo
    }

    return render(request, template_name="todos/todo-list.html#todo-list-item", context=context)


@require_http_methods(["DELETE"])
def todo_delete(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.delete()
    response = HttpResponse(status=204)
    response['HX-Trigger'] = 'todo-delete'
    return response

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.10/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/htmx.org@2.0.1" integrity="sha384-QWGpdj554B4ETpJJC9z+ZHJcA/i59TyjxEPXiiUgN2WmTyV5OEZWCD6gQhgkdpB/" crossorigin="anonymous"></script>
    {% block extra_header %}{% endblock extra_header %}
    <title>{% block title %}{% endblock title %}</title>
</head>

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    {% block content %}{% endblock content %}
    {% block extra_footer %}{% endblock extra_footer %}
</body>
</html>

todos/templates/todos/todo-list.html
{% extends "base.html" %}
{% load partials %}
{% load widget_tweaks %}

{% block title %}Todo List{% endblock title %}
{% block content %}
    <section class="container mx-auto">
        <button class="btn w-full my-2" onclick="todo_create.showModal()">Create Todo</button>
        <dialog id="todo_create" class="modal modal-bottom sm:modal-middle">
            <div class="modal-box">
                <h3 class="text-lg font-bold">Create Todo</h3>
                <form hx-on::after-request="this.reset(); todo_create.close();" hx-trigger="submit" hx-target="#todos" hx-swap="beforeend" hx-post="create/"
                      class="w-full flex flex-col gap-4 mt-4">
                    {% render_field form.title class+="input input-bordered w-full" placeholder="Title" %}
                    {% render_field form.description class+="textarea textarea-bordered w-full" placeholder="Description" %}
                    <div class="form-control">
                        <label class="label cursor-pointer">
                            <span class="label-text">Task is done</span>
                            {% render_field form.done class+="checkbox" %}
                        </label>
                    </div>
                    <div class="modal-action">
                        <div class="flex gap-2">
                            <button class="btn btn-error" type="button" onclick="todo_create.close()">Close</button>
                            <button class="btn btn-success" type="submit">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </dialog>
        <div class="overflow-x-auto">
            <table class="table table-zebra">
                <!-- head -->
                <thead>
                <tr>
                    <th></th>
                    <th>TITLE</th>
                    <th>DESCRIPTION</th>
                    <th>IS DONE</th>
                    <th>ACTIONS</th>
                </tr>
                </thead>
                <tbody id="todos">
                {% for todo in todos %}
                    {% partialdef todo-list-item inline=True %}
                        <tr>
                            <th>{{ todo.id }}</th>
                            <td>{{ todo.title }}</td>
                            <td>{{ todo.description }}</td>
                            <td>{{ todo.done }}</td>
                            <td class="flex gap-2">
                                <button
                                    class="btn btn-sm btn-error"
                                    hx-delete="{% url 'todos:todo-delete' todo.id %}"
                                    hx-on:todo-delete="this.closest('tr').remove()"
                                >DELETE</button>
                                {% if todo.done %}
                                    <button
                                        class="btn btn-sm btn-success"
                                        hx-post="{% url 'todos:todo-done-undone' todo.id %}"
                                        hx-target="closest tr"
                                        hx-swap="outerHTML"
                                    >UNDONE</button>
                                {% else %}
                                    <button
                                        class="btn btn-sm btn-success"
                                        hx-post="{% url 'todos:todo-done-undone' todo.id %}"
                                        hx-target="closest tr"
                                        hx-swap="outerHTML"
                                    >DONE</button>
                                {% endif %}
                            </td>
                        </tr>
                    {% endpartialdef %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock content %}